#!/usr/bin/env python3
"""Generate src/data/exportFiles.ts – the file list used by the ZIP exporter."""
import json, os

REPO = "/home/user/AndroidCafeBazaarWebView"

def read(path, default=""):
    full = os.path.join(REPO, path)
    return open(full, encoding="utf-8").read() if os.path.isfile(full) else default

def esc(text):
    return text.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")

files = [
    ("gradlew", read("gradlew")),
    ("gradlew.bat", read("gradlew.bat")),
    ("gradle/wrapper/gradle-wrapper.properties", read("gradle/wrapper/gradle-wrapper.properties")),
    (".gitignore", read(".gitignore")),
    ("local.properties.example", """; sdk.dir is machine specific – never commit the real local.properties.
; Native container configuration (all values stay in the native layer):
sdk.dir=/path/to/Android/sdk
TAPSELL_APP_KEY=
TAPSELL_ZONE_INTERSTITIAL=
TAPSELL_ZONE_REWARDED=
TAPSELL_ZONE_NATIVE=
PUSHFA_API_PUBLIC_KEY=
FIREBASE_APP_ID=
FIREBASE_API_KEY=
FIREBASE_PROJECT_ID=
FIREBASE_SENDER_ID=
"""),
]

out = []
out.append("// AUTO-GENERATED by tools/gen_export_files.py – files bundled into the exported ZIP.")
out.append("import { PROJECT_FILES } from './projectFiles';")
out.append("")
out.append("export interface ExportableFile {")
out.append("  path: string;")
out.append("  content: string;")
out.append("}")
out.append("")
out.append("export const EXTRA_PROJECT_FILES: ExportableFile[] = [")
for path, content in files:
    out.append("  {")
    out.append(f"    path: {json.dumps(path)},")
    out.append("    content: `" + esc(content) + "`")
    out.append("  },")
out.append("];")
out.append("")
out.append("/**")
out.append(" * Every file of the exportable project, de-duplicated by path.")
out.append(" * PROJECT_FILES wins over EXTRA_PROJECT_FILES for identical paths.")
out.append(" */")
out.append("export const ALL_EXPORT_FILES: ExportableFile[] = (() => {")
out.append("  const map = new Map<string, string>();")
out.append("  EXTRA_PROJECT_FILES.forEach(f => map.set(f.path, f.content));")
out.append("  PROJECT_FILES.forEach(f => map.set(f.path, f.content));")
out.append("  return Array.from(map.entries()).map(([path, content]) => ({ path, content }));")
out.append("})();")
out.append("")
open(os.path.join(REPO, "src/data/exportFiles.ts"), "w", encoding="utf-8").write("\n".join(out))
print("written src/data/exportFiles.ts")
