// AUTO-GENERATED by tools/gen_export_files.py – files bundled into the exported ZIP.
import { PROJECT_FILES } from './projectFiles';

export interface ExportableFile {
  path: string;
  content: string;
}

export const EXTRA_PROJECT_FILES: ExportableFile[] = [
  {
    path: "gradlew",
    content: `#!/bin/sh
APP_BASE_NAME=\`basename "$0"\`
APP_HOME="\`pwd -P\`"
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=\`ls -ld "$PRG"\`
    link=\`expr "$ls" : '.*-> \\(.*\\)$'\`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=\`dirname "$PRG"\`"/$link"
    fi
done
SAVED="\`pwd\`"
cd "\`dirname \\"$PRG\\"\`/" >/dev/null
APP_HOME="\`pwd -P\`"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    mkdir -p "$APP_HOME/gradle/wrapper"
    curl -fsSL https://raw.githubusercontent.com/gradle/gradle/v8.5.0/gradle/wrapper/gradle-wrapper.jar -o "$CLASSPATH" 2>/dev/null || true
fi

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2; exit 1; }
fi

exec "$JAVACMD" "-Dorg.gradle.appname=$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
`
  },
  {
    path: "gradlew.bat",
    content: `@if "%DEBUG%"=="" @echo off
if "%OS%"=="Windows_NT" setlocal
set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi
set DEFAULT_JVM_OPTS=-Dfile.encoding=UTF-8 "-Xmx64m" "-Xms64m"

if defined JAVA_HOME goto findJavaFromJavaHome
set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if %ERRORLEVEL% equ 0 goto execute
echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.
goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe
if exist "%JAVA_EXE%" goto execute
echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo.
echo Please set the JAVA_HOME variable in your environment to match the
echo location of your Java installation.
goto fail

:execute
set CLASSPATH=%APP_HOME%\\gradle\\wrapper\\gradle-wrapper.jar
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% "-Dorg.gradle.appname=%APP_BASE_NAME%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
:end
if %ERRORLEVEL% equ 0 goto mainEnd
:fail
set EXIT_CODE=%ERRORLEVEL%
if %EXIT_CODE% equ 0 set EXIT_CODE=1
exit /b %EXIT_CODE%
:mainEnd
if "%OS%"=="Windows_NT" endlocal
`
  },
  {
    path: "gradle/wrapper/gradle-wrapper.properties",
    content: `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.5-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`
  },
  {
    path: ".gitignore",
    content: `node_modules/
build/
dist/
coverage/
.DS_Store
*.log
.env*
!.env.example
package-lock.json
.gradle/
.idea/
*.iml
app/release/
__pycache__/
*.pyc
`
  },
  {
    path: "local.properties.example",
    content: `; sdk.dir is machine specific – never commit the real local.properties.
; Native container configuration (all values stay in the native layer):
sdk.dir=/path/to/Android/sdk
TAPSELL_APP_KEY=
TAPSELL_ZONE_INTERSTITIAL=
TAPSELL_ZONE_REWARDED=
TAPSELL_ZONE_NATIVE=
PUSHFA_API_PUBLIC_KEY=
FIREBASE_APP_ID=
FIREBASE_API_KEY=
FIREBASE_PROJECT_ID=
FIREBASE_SENDER_ID=
`
  },
];

/**
 * Every file of the exportable project, de-duplicated by path.
 * PROJECT_FILES wins over EXTRA_PROJECT_FILES for identical paths.
 */
export const ALL_EXPORT_FILES: ExportableFile[] = (() => {
  const map = new Map<string, string>();
  EXTRA_PROJECT_FILES.forEach(f => map.set(f.path, f.content));
  PROJECT_FILES.forEach(f => map.set(f.path, f.content));
  return Array.from(map.entries()).map(([path, content]) => ({ path, content }));
})();
